print("Hello, this program will ask you for two numbers and will then perform several calculations on the two numbers")
n1 = float(input("Enter your first number: "))
n2 = float(input("Enter your second number: "))
print(f"Adding your two numbers gives us {n1 + n2}")
print(f"Subtracting your two numbers gives us {n1 - n2}")
print(f"Multiplying your two numbers gives us {n1 * n2}")
print(f"Dividing your two numbers gives us {n1 / n2}")
print(f"Dividing your two numbers with a remainder gives us {n1 % n2}")
print(f"Raising your first number to the second gives us {n1 ** n2}")
